-- =============================================================================
-- backtest_runs
-- One row per completed backtest execution.
-- summary_text is auto-generated by Claude immediately after each run
-- and stored with its embedding for RAG retrieval.
-- Populated by the backtesting engine (Phase 1) and AI summary (Phase 2).
-- =============================================================================

CREATE TABLE IF NOT EXISTS backtest_runs (
    id            UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    strategy_id   UUID          NOT NULL REFERENCES strategies(id),
    period_start  DATE          NOT NULL,
    period_end    DATE          NOT NULL,
    pair          VARCHAR(10)   NOT NULL,
    timeframe     VARCHAR(5)    NOT NULL,

    -- Performance metrics
    sharpe        NUMERIC(10, 4),
    sortino       NUMERIC(10, 4),
    max_dd        NUMERIC(10, 4),      -- max drawdown as a decimal (e.g. 0.15 = 15%)
    win_rate      NUMERIC(10, 4),      -- decimal (e.g. 0.55 = 55%)
    avg_r         NUMERIC(10, 4),      -- average R-multiple
    trade_count   INTEGER,
    total_pnl     NUMERIC(18, 4),

    -- AI-generated prose summary (auto-created by Claude after each run)
    -- Describes when the strategy worked, when it failed, and under what conditions.
    summary_text  TEXT,
    embedding     vector(1024),         -- Voyage AI embedding of summary_text (RAG)

    created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

-- Retrieve all runs for a strategy in reverse chronological order
CREATE INDEX IF NOT EXISTS idx_backtest_runs_strategy
    ON backtest_runs (strategy_id, created_at DESC);

-- Retrieve runs for a specific pair (cross-strategy analytics)
CREATE INDEX IF NOT EXISTS idx_backtest_runs_pair
    ON backtest_runs (pair, created_at DESC);

-- Full-text search on AI-generated summaries
ALTER TABLE backtest_runs
    ADD COLUMN IF NOT EXISTS summary_tsv tsvector
    GENERATED ALWAYS AS (to_tsvector('english', COALESCE(summary_text, ''))) STORED;

CREATE INDEX IF NOT EXISTS idx_backtest_runs_fts
    ON backtest_runs USING GIN (summary_tsv);

-- IVFFlat index for vector similarity search on summaries
CREATE INDEX IF NOT EXISTS idx_backtest_runs_embedding
    ON backtest_runs USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100);
